fixtures:
  repositories:
    apt:
      repo: https://github.com/puppetlabs/puppetlabs-apt.git
      ref: v9.1.0
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: v9.3.0
    datacat:
      repo: https://github.com/richardc/puppet-datacat.git
      ref: 0.6.2
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core
      ref: v2.0.0
      puppet_version: ">= 6.0.0"
    chocolatey:
      repo: https://github.com/puppetlabs/puppetlabs-chocolatey.git
      ref: v8.0.0
    # Needed by chocolatey
    registry:
      repo: https://github.com/puppetlabs/puppetlabs-registry.git
      ref: v5.0.1
    # Needed by chocolatey
    powershell:
      repo: https://github.com/puppetlabs/puppetlabs-powershell.git
      ref: v6.0.0
    # Need by postgresql
    augeas_core:
      repo: https://github.com/puppetlabs/puppetlabs-augeas_core
      ref: v1.4.0
      puppet_version: ">= 6.0.0"
    # Need by postgresql
    concat:
      repo: https://github.com/puppetlabs/puppetlabs-concat.git
      ref: v9.0.0
    postgresql:
      repo: https://github.com/puppetlabs/puppetlabs-postgresql.git
      ref: v9.1.0
    archive:
      repo: https://github.com/voxpupuli/puppet-archive.git
      ref: v7.0.0
    windows_env:
      repo: https://github.com/voxpupuli/puppet-windows_env.git
      ref: v5.0.0
    systemd:
      repo: https://github.com/camptocamp/puppet-systemd.git
      ref: v8.3.0
  symlinks:
    sensu: "#{source_dir}"
