fixtures:
  repositories:
    apt:
      repo: git://github.com/puppetlabs/puppetlabs-apt.git
      ref: 4.1.0
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.24.0
    remote_file:
      repo: git://github.com/lwf/puppet-remote_file.git
      ref: v1.1.3
    dsc:
      repo: git://github.com/puppetlabs/puppetlabs-dsc.git
      ref: 1.4.1
    acl:
      repo: git://github.com/puppetlabs/puppetlabs-acl.git
      ref: 2.0.1
    powershell:
      repo: git://github.com/puppetlabs/puppetlabs-powershell.git
      ref: 2.1.0
  symlinks:
    sensu: "#{source_dir}"
