version '0.5.0'
name 'sensu-puppet'
dependency 'puppetlabs/apt'
dependency 'puppetlabs/rabbitmq'
dependency 'thomasvandoren/redis'
license 'MIT'
summary 'A module to intall the Sensu monitoring framework'
project_page 'https://github.com/sensu/sensu-puppet'
