name: Acceptance cluster

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  acceptance-cluster:
    runs-on: ubuntu-latest
    # Items marked as ci_build=yes are allowed to fail
    continue-on-error: ${{ matrix.ci_build == 'yes' }}
    strategy:
      fail-fast: false
      matrix:
        puppet:
        - puppet6
        - puppet7
        use_agent:
        - no
        - yes
        ci_build:
        - no
    env:
      BEAKER_debug: true
    name: Sensu Go Cluster ${{ matrix.puppet }} (use-agent=${{ matrix.use_agent }} CI=${{ matrix.ci_build }})
    steps:
    - uses: actions/checkout@v4
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        rubygems: 'latest'
        bundler: 'latest'
        bundler-cache: true
    - name: Decrypt secrets
      env:
        SENSU_SECRETS_PASSWORD: ${{ secrets.SENSU_SECRETS_PASSWORD }}
      if: ${{ env.SENSU_SECRETS_PASSWORD != null }}
      run: ./tests/decrypt-secrets.sh
    - name: Run tests
      run: bundle exec rake acceptance
      env:
        BEAKER_PUPPET_COLLECTION: ${{ matrix.puppet }}
        BEAKER_set: centos-7-cluster
        BEAKER_sensu_mode: cluster
        BEAKER_sensu_use_agent: ${{ matrix.use_agent }}
        BEAKER_sensu_ci_build: ${{ matrix.ci_build }}
