name: Unit

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    continue-on-error: ${{ matrix.allow_failure }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: '3.4'
          puppet: 8
          fixtures: .fixtures.yml
          allow_failure: false
    env:
      BUNDLE_WITHOUT: system_tests:development
      PUPPET_GEM_VERSION: "~> ${{ matrix.puppet }}.0"
      FIXTURES_YML: ${{ matrix.fixtures }}
    name: Puppet ${{ matrix.puppet }} (Ruby ${{ matrix.ruby }} fixtures=${{ matrix.fixtures }})
    steps:
      - uses: actions/checkout@v7
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Validate
        run: bundle exec rake sensu_validate lint
      - name: Run tests
        run: bundle exec rake spec
