name: Unit

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    # Items marked as allow_failure=true are allowed to fail
    # This is fixtures using latest untagged versions
    continue-on-error: ${{ matrix.allow_failure }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: '3.1'
          puppet: 7
          fixtures: .fixtures.yml
          allow_failure: false
        - ruby: '3.2'
          puppet: 7
          fixtures: .fixtures.yml
          allow_failure: false
        - ruby: '3.1'
          puppet: 7
          fixtures: .fixtures-latest.yml
          allow_failure: true
        - ruby: '3.2'
          puppet: 8
          fixtures: .fixtures-latest.yml
          allow_failure: true
    env:
      BUNDLE_WITHOUT: system_tests:development
      PUPPET_GEM_VERSION: "~> ${{ matrix.puppet }}.0"
      FIXTURES_YML: ${{ matrix.fixtures }}
    name: Puppet ${{ matrix.puppet }} (Ruby ${{ matrix.ruby }} fixtures=${{ matrix.fixtures }})
    steps:
      - uses: actions/checkout@v4
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          rubygems: 'latest'
          bundler: 'latest'
          bundler-cache: true
      - name: Validate
        run: bundle exec rake sensu_validate lint strings:generate reference
      - name: Run tests
        run: bundle exec rake parallel_spec
